### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by playdasegunda** [junyuchen-cjy/DTTNet-Pytorch#2]
I'm trying to start the training, but I'm getting this error and I don't know how to solve it, thanks in advance.

```
(DTT) root@nxljan5kzq:/notebooks/DTTNet-Pytorch# python train.py experiment=vocals_dis datamodule=musdb_dev14 trainer=default
/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
datamodule:
  _target_: src.datamodules.musdb_datamodule.MusdbDataModule
  data_dir: ${oc.env:data_dir}
  single_channel: false
  sample_rate: 44100
  hop_length: ${model.hop_length}
  dim_t: ${model.dim_t}
  overlap: ${model.overlap}
  source_names:
  - bass
  - drums
  - other
  - vocals
  target_name: ${model.target_name}
  external_datasets: null
  batch_size: 8
  num_workers: ${oc.decode:${oc.env:NUM_WORKERS}}
  pin_memory: false
  aug_params:
  - 2
  - 20
  validation_set:
  - aaakqpjby
  - aagyznonrakr
  - aambuiyyh
  - aazblows
  - acpggfbphom
  - aczmumavryin
  - adahirwcds
  - adiqeobfhpuf
  - aembtwusnq
  - afxbktvhrzl
  - ahiqyfajtxt
  - amteslzq
  - aoikkulp
  - aovpecpibt
  has_split_structure: true
  mode: musdb18hq
  audio_ch: ${model.audio_ch}
  epoch_size: null
model:
  _target_: src.dp_tdf.dp_tdf_net.DPTDFNet
  target_name: vocals
  lr: 0.0002
  optimizer: adamW
  dim_f: 2048
  dim_t: 256
  n_fft: 6144
  hop_length: 1024
  overlap: 3072
  audio_ch: 2
  block_type: TFC_TDF_Res2
  num_blocks: 5
  l: 3
  g: 32
  k: 3
  bn: 8
  bias: false
  bn_norm: syncBN
  bandsequence:
    rnn_type: LSTM
    bidirectional: true
    num_layers: 4
    n_heads: 2
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/usdr
    save_top_k: 5
    save_last: true
    mode: max
    verbose: false
    dirpath: checkpoints/
    filename: '{epoch:02d}-{step}'
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: dtt_${model.target_name}
    name: ${exp_name}
    save_dir: ${hydra:run.dir}
    offline: false
    id: null
    log_model: false
    prefix: ''
    job_type: train
    group: ''
    tags: []
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: tensorboard/
    name: default
    version: null
    log_graph: false
    default_hp_metric: true
    prefix: ''
trainer:
  _target_: pytorch_lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 1000000
  accelerator: cuda
  devices: 2
  check_val_every_n_epoch: 1
  deterministic: false
  amp_backend: native
  precision: 16
  track_grad_norm: 2
  sync_batchnorm: true
paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${oc.env:LOG_DIR}
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
seed: 2021
exp_name: vocals_g32
debug: false
print_config: true
ignore_warnings: true
wandb_api_key: ${oc.env:wandb_api_key}

[2023-12-27 18:19:51,614][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
[2023-12-27 18:19:51,614][src.utils.rich_utils][WARNING] - Field 'data' not found in config. Skipping 'data' config printing...
[2023-12-27 18:19:51,615][src.utils.rich_utils][WARNING] - Field 'extras' not found in config. Skipping 'extras' config printing...
CONFIG
├── model
│   └── _target_: src.dp_tdf.dp_tdf_net.DPTDFNet                                                                                                       
│       target_name: vocals                                                                                                                            
│       lr: 0.0002                                                                                                                                     
│       optimizer: adamW                                                                                                                               
│       dim_f: 2048                                                                                                                                    
│       dim_t: 256                                                                                                                                     
│       n_fft: 6144                                                                                                                                    
│       hop_length: 1024                                                                                                                               
│       overlap: 3072                                                                                                                                  
│       audio_ch: 2                                                                                                                                    
│       block_type: TFC_TDF_Res2                                                                                                                       
│       num_blocks: 5                                                                                                                                  
│       l: 3                                                                                                                                           
│       g: 32                                                                                                                                          
│       k: 3                                                                                                                                           
│       bn: 8                                                                                                                                          
│       bias: false                                                                                                                                    
│       bn_norm: syncBN                                                                                                                                
│       bandsequence:                                                                                                                                  
│         rnn_type: LSTM                                                                                                                               
│         bidirectional: true                                                                                                                          
│         num_layers: 4                                                                                                                                
│         n_heads: 2                                                                                                                                   
│                                                                                                                                                      
├── callbacks
│   └── model_checkpoint:                                                                                                                              
│         _target_: pytorch_lightning.callbacks.ModelCheckpoint                                                                                        
│         monitor: val/usdr                                                                                                                            
│         save_top_k: 5                                                                                                                                
│         save_last: true                                                                                                                              
│         mode: max                                                                                                                                    
│         verbose: false                                                                                                                               
│         dirpath: checkpoints/                                                                                                                        
│         filename: '{epoch:02d}-{step}'                                                                                                               
│                                                                                                                                                      
├── logger
│   └── wandb:                                                                                                                                         
│         _target_: pytorch_lightning.loggers.wandb.WandbLogger                                                                                        
│         project: dtt_vocals                                                                                                                          
│         name: vocals_g32                                                                                                                             
│         save_dir: /notebooks/DTTNet-Pytorch/checkpoints/vocals_vocals_g32_7                                                                          
│         offline: false                                                                                                                               
│         id: null                                                                                                                                     
│         log_model: false                                                                                                                             
│         prefix: ''                                                                                                                                   
│         job_type: train                                                                                                                              
│         group: ''                                                                                                                                    
│         tags: []                                                                                                                                     
│       tensorboard:                                                                                                                                   
│         _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger                                                                            
│         save_dir: tensorboard/                                                                                                                       
│         name: default                                                                                                                                
│         version: null                                                                                                                                
│         log_graph: false                                                                                                                             
│         default_hp_metric: true                                                                                                                      
│         prefix: ''                                                                                                                                   
│                                                                                                                                                      
├── trainer
│   └── _target_: pytorch_lightning.Trainer                                                                                                            
│       default_root_dir: /notebooks/DTTNet-Pytorch/checkpoints/vocals_vocals_g32_7                                                                    
│       min_epochs: 1                                                                                                                                  
│       max_epochs: 1000000                                                                                                                            
│       accelerator: cuda                                                                                                                              
│       devices: 2                                                                                                                                     
│       check_val_every_n_epoch: 1                                                                                                                     
│       deterministic: false                                                                                                                           
│       amp_backend: native                                                                                                                            
│       precision: 16                                                                                                                                  
│       track_grad_norm: 2                                                                                                                             
│       sync_batchnorm: true                                                                                                                           
│                                                                                                                                                      
├── paths
│   └── root_dir: /notebooks/DTTNet-Pytorch                                                                                                            
│       data_dir: /notebooks/DTTNet-Pytorch/data/                                                                                                      
│       log_dir: /notebooks/DTTNet-Pytorch/checkpoints                                                                                                 
│       output_dir: /notebooks/DTTNet-Pytorch/checkpoints/vocals_vocals_g32_7                                                                          
│       work_dir: /notebooks/DTTNet-Pytorch                                                                                                            
│                                                                                                                                                      
├── datamodule
│   └── _target_: src.datamodules.musdb_datamodule.MusdbDataModule                                                                                     
│       data_dir: /notebooks/DTTNet-Pytorch/dataset                                                                                                    
│       single_channel: false                                                                                                                          
│       sample_rate: 44100                                                                                                                             
│       hop_length: 1024                                                                                                                               
│       dim_t: 256                                                                                                                                     
│       overlap: 3072                                                                                                                                  
│       source_names:                                                                                                                                  
│       - bass                                                                                                                                         
│       - drums                                                                                                                                        
│       - other                                                                                                                                        
│       - vocals                                                                                                                                       
│       target_name: vocals                                                                                                                            
│       external_datasets: null                                                                                                                        
│       batch_size: 8                                                                                                                                  
│       num_workers: 0                                                                                                                                 
│       pin_memory: false                                                                                                                              
│       aug_params:                                                                                                                                    
│       - 2                                                                                                                                            
│       - 20                                                                                                                                           
│       validation_set:                                                                                                                                
│       - aaakqpjby                                                                                                                                    
│       - aagyznonrakr                                                                                                                                 
│       - aambuiyyh                                                                                                                                    
│       - aazblows                                                                                                                                     
│       - acpggfbphom                                                                                                                                  
│       - aczmumavryin                                                                                                                                 
│       - adahirwcds                                                                                                                                   
│       - adiqeobfhpuf                                                                                                                                 
│       - aembtwusnq                                                                                                                                   
│       - afxbktvhrzl                                                                                                                                  
│       - ahiqyfajtxt                                                                                                                                  
│       - amteslzq                                                                                                                                     
│       - aoikkulp                                                                                                                                     
│       - aovpecpibt                                                                                                                                   
│       has_split_structure: true                                                                                                                      
│       mode: musdb18hq                                                                                                                                
│       audio_ch: 2                                                                                                                                    
│       epoch_size: null                                                                                                                               
│                                                                                                                                                      
├── seed
│   └── 2021                                                                                                                                           
├── exp_name
│   └── vocals_g32                                                                                                                                     
├── debug
│   └── False                                                                                                                                          
├── print_config
│   └── True                                                                                                                                           
├── ignore_warnings
│   └── True                                                                                                                                           
└── wandb_api_key
    └── XXXXX                                                                                                       
[2023-12-27 18:19:51,667][src.utils.utils][WARNING] - Extras config not found! <cfg.extras=null>
Global seed set to 2021
[2023-12-27 18:19:51,669][src.train][INFO] - Instantiating datamodule <src.datamodules.musdb_datamodule.MusdbDataModule>
[2023-12-27 18:19:51,680][src.train][INFO] - Instantiating model <src.dp_tdf.dp_tdf_net.DPTDFNet>
/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/functional.py:632: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/SpectralOps.cpp:801.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
[2023-12-27 18:19:51,769][src.train][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2023-12-27 18:19:51,771][src.train][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
wandb: Currently logged in as: lucasrod1000. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /notebooks/DTTNet-Pytorch/checkpoints/vocals_vocals_g32_7/wandb/run-20231227_181952-kmqw4nqn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vocals_g32
wandb: ⭐️ View project at https://wandb.ai/lucasrod1000/dtt_vocals
wandb: 🚀 View run at https://wandb.ai/lucasrod1000/dtt_vocals/runs/kmqw4nqn
[2023-12-27 18:19:55,073][src.train][INFO] - Instantiating logger <pytorch_lightning.loggers.tensorboard.TensorBoardLogger>
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
[2023-12-27 18:19:55,080][src.train][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:395: LightningDeprecationWarning: The NVIDIA/apex AMP implementation has been deprecated upstream. Consequently, its integration inside PyTorch Lightning has been deprecated in v1.9.0 and will be removed in v2.0.0. The `Trainer(amp_backend='native')` argument is deprecated. Removing this argument will avoid this message, it will select PyTorch's implementation automatically.
  rank_zero_deprecation(
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2023-12-27 18:19:55,248][src.train][INFO] - Logging hyperparameters!
[2023-12-27 18:19:55,321][src.train][INFO] - Starting training!
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
0it [00:00, ?it/s]creating metadata for /notebooks/DTTNet-Pytorch/dataset/train_p=-2_t=-20
0it [00:00, ?it/s]
[2023-12-27 18:20:03,724][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/notebooks/DTTNet-Pytorch/src/utils/utils.py", line 48, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/notebooks/DTTNet-Pytorch/src/train.py", line 127, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/notebooks/DTTNet-Pytorch/src/datamodules/datasets/musdb.py", line 85, in __init__
    metadata = torch.load(metadata_cache)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/DTTNet-Pytorch/dataset/metadata/train_p=-2_t=-20.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 139, in _wrapping_function
    results = function(*args, **kwargs)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1042, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1366, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/notebooks/DTTNet-Pytorch/src/datamodules/musdb_datamodule.py", line 86, in setup
    self.data_train = MusdbTrainDataset(self.data_dir,
  File "/notebooks/DTTNet-Pytorch/src/datamodules/datasets/musdb.py", line 89, in __init__
    for track_name in sorted(os.listdir(dataset)):
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/DTTNet-Pytorch/dataset/train_p=-2_t=-20'

[2023-12-27 18:20:03,728][src.utils.utils][INFO] - Output dir: /notebooks/DTTNet-Pytorch/checkpoints/vocals_vocals_g32_7
[2023-12-27 18:20:03,728][src.utils.utils][INFO] - Closing loggers...
[2023-12-27 18:20:03,728][src.utils.utils][INFO] - Closing wandb!
wandb:                                                                                
wandb: W&B sync reduced upload amount by 8.2%             
wandb: 🚀 View run vocals_g32 at: https://wandb.ai/lucasrod1000/dtt_vocals/runs/kmqw4nqn
wandb: ️⚡ View job at https://wandb.ai/lucasrod1000/dtt_vocals/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEyNTk1MDM4MA==/version_details/v2
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231227_181952-kmqw4nqn/logs
Error executing job with overrides: ['experiment=vocals_dis', 'datamodule=musdb_dev14', 'trainer=default']
Traceback (most recent call last):
  File "/notebooks/DTTNet-Pytorch/train.py", line 44, in <module>
    main()
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/notebooks/DTTNet-Pytorch/train.py", line 36, in main
    train(config)
  File "/notebooks/DTTNet-Pytorch/src/utils/utils.py", line 58, in wrap
    raise ex
  File "/notebooks/DTTNet-Pytorch/src/utils/utils.py", line 48, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/notebooks/DTTNet-Pytorch/src/train.py", line 127, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/notebooks/DTTNet-Pytorch/src/datamodules/datasets/musdb.py", line 85, in __init__
    metadata = torch.load(metadata_cache)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/DTTNet-Pytorch/dataset/metadata/train_p=-2_t=-20.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 139, in _wrapping_function
    results = function(*args, **kwargs)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1042, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/root/anaconda3/envs/DTT/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1366, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/notebooks/DTTNet-Pytorch/src/datamodules/musdb_datamodule.py", line 86, in setup
    self.data_train = MusdbTrainDataset(self.data_dir,
  File "/notebooks/DTTNet-Pytorch/src/datamodules/datasets/musdb.py", line 89, in __init__
    for track_name in sorted(os.listdir(dataset)):
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/DTTNet-Pytorch/dataset/train_p=-2_t=-20'
```

**Comment by lucasbr15** [comment]
**SOME OTHER OBSERVATIONS**:

the .env file is configured as follows:

```
# the folder of musdb18hq dataset, contains train and test folders
data_dir=/notebooks/DTTNet-Pytorch/dataset

PROJECT_ROOT=/notebooks/DTTNet-Pytorch

# the directory where the checkpoints will be saved
LOG_DIR=/notebooks/DTTNet-Pytorch/checkpoints

# You don't have to fill this if you want to use tensorboard only.
wandb_api_key=XXXX # go wandb.ai/settings and copy your key

# Number of cores of your cpu, will be used in dataloaders
NUM_WORKERS=0

HYDRA_FULL_ERROR=1
```

This is the format of my dataset and validationset:

/notebooks/DTTNet-Pytorch/dataset/test
/notebooks/DTTNet-Pytorch/dataset/train
/notebooks/DTTNet-Pytorch/dataset/valid

**/notebooks/DTTNet-Pytorch/dataset/test/AM Contra - Heart Peripheral:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_

**/notebooks/DTTNet-Pytorch/dataset/test/Al James - Schoolboy Facination:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_

**/notebooks/DTTNet-Pytorch/dataset/train/argbrtkfktq:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_

**/notebooks/DTTNet-Pytorch/dataset/train/arxkijpknte:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_

**/notebooks/DTTNet-Pytorch/dataset/valid/aaakqpjby:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_

**/notebooks/DTTNet-Pytorch/dataset/valid/aagyznonrakr:**
_bass.wav, drums.wav, mixture.wav, other.wav, vocals.wav_
...

And the DTTNet-Pytorch/configs/datamodule/musdb_dev14.yaml file looks like this:

```yaml

defaults:
  - musdb18_hq

data_dir: ${oc.env:data_dir}

has_split_structure: True

validation_set:
  - aaakqpjby
  - aambuiyyh
  - acpggfbphom
  - adahirwcds
  - aembtwusnq
  - ahiqyfajtxt
  - aoikkulp
  - aagyznonrakr
  - aazblows
  - aczmumavryin
  - adiqeobfhpuf
  - afxbktvhrzl
  - amteslzq
  - aovpecpibt

mode: musdb18hqa
```

**Comment by lucasbr15** [comment]
Apparently the problem has been resolved and training has begun. I am using 2x A100-40GB for training, and each epoch is being completed in approximately 7m22s, is this average time expected? Another question, how many days did it take for the `vocalsg32_ep4082.ckpt` model to be trained?

![Screenshot_1](https://github.com/junyuchen-cjy/DTTNet-Pytorch/assets/97372669/f48d479b-b11f-4729-a9ef-b45aae6d23b9)

**Comment by lucasbr15** [comment]
solved

**Comment by junyuchen-cjy** [comment]
> ~Apparently the problem has been resolved and training has begun. I am using 2x A100-40GB for training, and each epoch is being completed in approximately 7m22s, is this average time expected? Another question, how many days did it take for the `vocalsg32_ep4082.ckpt` model to be trained?~
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/97372669/293135600-f48d479b-b11f-4729-a9ef-b45aae6d23b9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDIzNjQsIm5iZiI6MTcwNDM0MjA2NCwicGF0aCI6Ii85NzM3MjY2OS8yOTMxMzU2MDAtZjQ4ZDQ3OWItYjExZi00NzI5LWE5ZWYtYjQ1YWFlNmQyM2I5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA0MjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkN2FiMGEyNTBiNGMxMjRmMDhmMDYzZTQzNzYzZmIxZWEwNGIwOGJiZWU0MTEzZDBhMWExMmQ2ZmIxNjFiNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDLhDD2RDrYcgdad0iLxcOrxLjDE_L0f8mIHnmNyOmI)

Sorry for my late reply. 7 min/epoch might be slow; we achieved 3-4 min/epoch over 15 days (4082 epochs). For faster results, please consider upgrading to 80GB+ RAM, using SSD for dataset storage, and increasing num_workers for the dataloader (10, with a 15+ cores CPU).
